-- Phase 1: authentication tables and the schema fixes agreed on 2 October 2026.

-- Fair draw ----------------------------------------------------------------
-- Payout positions are assigned by the commit-reveal draw once a circle is
-- full, so a member's position stays empty ("not yet drawn") until then.
-- The unique (group_id, payout_position) constraint still applies; NULLs
-- don't clash.
alter table group_members alter column payout_position drop not null;

-- The admin may pledge to collect last; the draw respects the pledge.
alter table groups add column if not exists admin_collects_last boolean not null default false;

-- Invite codes ---------------------------------------------------------------
-- Codes are generated by the API from an alphabet without look-alike
-- characters (no 0/O, 1/I/L). The old md5-based default produced hex codes.
alter table groups alter column invite_code drop default;
alter table groups add constraint groups_invite_code_format
  check (invite_code ~ '^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{6}$');

-- Payout amount ------------------------------------------------------------
-- The collector receives from the other members: contribution x (members - 1).
-- The shortfall is measured against that, not against whatever happened to be
-- confirmed, so unpaid members show up as a shortfall.
create or replace function confirm_payout(p_round_id uuid, p_user_id uuid, p_amount int)
returns int
language plpgsql as $$
declare
  r         rounds%rowtype;
  g         groups%rowtype;
  members   int;
  expected  int;
begin
  if p_amount < 0 then raise exception 'amount cannot be negative'; end if;
  select * into r from rounds where id = p_round_id for update;
  if not found then raise exception 'round not found'; end if;
  if r.collector_id <> p_user_id then raise exception 'only this round''s collector can confirm the payout'; end if;
  if r.payout_confirmed_at is not null then raise exception 'the payout for this round is already confirmed'; end if;

  select * into g from groups where id = r.group_id;
  select count(*) into members from group_members where group_id = r.group_id;
  expected := g.contribution_amount * greatest(members - 1, 0);

  update rounds set payout_received = p_amount, payout_confirmed_at = now() where id = p_round_id;
  return greatest(expected - p_amount, 0);
end $$;

-- Accounts -------------------------------------------------------------------
-- Marks the seeded demo account used by "Try the demo".
alter table users add column if not exists is_demo boolean not null default false;

-- One-time codes sent to a phone. Only an HMAC of the code is stored.
create table if not exists otp_challenges (
  id           uuid primary key default gen_random_uuid(),
  phone        text not null check (phone ~ '^\+234[789][01]\d{8}$'),
  code_hash    text not null,
  expires_at   timestamptz not null,
  attempts     int not null default 0 check (attempts >= 0),
  consumed_at  timestamptz,
  created_at   timestamptz not null default now()
);
create index if not exists otp_challenges_phone_idx on otp_challenges (phone, created_at desc);

-- Refresh-token sessions. Tokens rotate on every refresh; presenting a token
-- that was already rotated revokes its whole family (stolen-token detection).
-- Only a SHA-256 of each token is stored.
create table if not exists sessions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references users(id) on delete cascade,
  family_id    uuid not null,
  token_hash   text not null unique,
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  revoked_at   timestamptz,
  replaced_by  uuid references sessions(id),
  user_agent   text check (char_length(user_agent) <= 300)
);
create index if not exists sessions_user_idx on sessions (user_id) where revoked_at is null;
create index if not exists sessions_family_idx on sessions (family_id);
